sudo: required
services:
        - docker

before_install:
        - docker build -t ashita12/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true ashita12/docker-react npm run test


